name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: macos-latest
    steps:
      - run: echo "🎉 starting to install CLI"
      - run: brew tap shopify/shopify
      - run: brew install shopify-cli
      - run: shopify version
